DROP TABLE tbl_alumini;

CREATE TABLE `tbl_alumini` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `alumininame` varchar(100) NOT NULL,
  `aluminiyearofpassing` varchar(4) NOT NULL,
  `aluminicurrentlyworkingin` varchar(100) NOT NULL,
  `aluminimobileno` varchar(12) NOT NULL,
  `aluminiemailId` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

INSERT INTO tbl_alumini VALUES("16","Abhijit Sarwagod","2013","TCS","9960828312","abhijit.sarvagod@gmail.com");



DROP TABLE tbl_contactus;

CREATE TABLE `tbl_contactus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  `email` text COLLATE utf8_unicode_ci NOT NULL,
  `contact` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `subject` text COLLATE utf8_unicode_ci NOT NULL,
  `message` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=195 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO tbl_contactus VALUES("69","Julienne Row","julienne.row@googlemail.com","Myxyocsb","We Want to Buy Directly from You!","Hello\n \nWe to buy directly from you. We specialize in turning toys into cash.\n \nSell your excess, overstock, liquid-able or personal collection of Ty Beanie Babies and other plush toys to us... \n \nFREE SHIPPING - NO FEE TO SELL - SAFE & SECURE- QUICK & EASY\n \nTurn your toys into cash today! ==>  http://bit.ly/2Pd70wg");
INSERT INTO tbl_contactus VALUES("70","Rhys Sennitt","noreply@thewordpressclub9583.pro","Q nj i ql","Question","Hi There,\n\nAre you presently using Wordpress/Woocommerce or maybe do you actually plan to use it eventually ? We currently provide more than 2500 premium plugins but also themes 100 percent free to download : http://squick.xyz/BGcMf\n\nThanks,\n\nRhys");
INSERT INTO tbl_contactus VALUES("71","Aisha Olden","olden.aisha@gmail.com","N y Syofvy","YOU NEED TRAFFIC From Search Engines In Any Country for dkkkpmba.com","Hello\n \nYOU NEED QUALITY ORGANIC TRAFFIC THAT BUY FROM YOU ??\n100% Safe Organic Traffic from search engines in any country for dkkkpmba.com\n \nIF YOU ARE INTERESTED\nCONTACT US =>   multimp@mail.com\n \nRegards,\nAxyyKo");
INSERT INTO tbl_contactus VALUES("72","Lucas Weber","info@wrldclass-solutions.com","Uurgl u","You are IGNORING 75% of your Visitors","How would you like to Upload A SINGLE Video And\nRANK for 100 LANGUAGES !!!\n\nFACT #1\n\nONLY 25% of the searches made online are in ENGLISH!\nAnd yet everybody focuses on trying to rank in ENGLISH!\n\nFACT #2\nYouTube is the 2nd BIGGEST website in the world…\nAnd still you focus all your efforts trying to rank and get traffic ONLY from Google!\n\nhttp://wrldclass-solutions.com\n\nDO THE MATH:\n\nWith Over 3 Billion Searches A Month…\n\nAll the visitors that you will ever need\nARE ALREADY ON YOUTUBE!\n\n3 billion searches a month.\n75% are not in English…\nDo the math… 2.2 billion searches each month in foreign languages!\n\nAre you getting an idea on how much money you are leaving on the TABLE?\n\nhttp://wrldclass-solutions.com");
INSERT INTO tbl_contactus VALUES("73","Deana Mark","deana.mark@gmail.com","Fdqmfdbgvm","You Need Leads, Sales, Conversions, Traffic for your site ?","Hi there\n \nI will Find Leads that Buy From You\nI will Promote Your Business In Any Country To Any Niche.\n==>   https://is.gd/wS4dZp\n \nRegards");
INSERT INTO tbl_contactus VALUES("74","Carson Lilley","noreply@gplforest7261.xyz","Xh Opxk m","Question","Hi There,\n\nAre you currently utilising Wordpress/Woocommerce or maybe do you actually project to work with it later ? We currently offer a little over 2500 premium plugins and also themes totally free to get : http://urlru.xyz/Chirs\n\nThank You,\n\nCarson");
INSERT INTO tbl_contactus VALUES("75","Carmine Monahan","carmine.monahan@hotmail.com","Td Zqlcs L","NEW WAY to generate quick TRAFFIC and SALES in ANY niche with ZERO video/website creation, ZERO paid advertising/SEO.","Hello,\n \nTIRED OF WAITING FOREVER TO EARN A PROFIT ONLINE ?\n \nMy name is Carmine Monahan and I’m talking about a new way to generate quick traffic and sales in ANY niche with ZERO video/website creation, ZERO paid advertising/SEO. \n \nI’ve recently tried this product but quickly decide to write this review because I know this is exactly what you  are looking for your dkkkpmba.com \n \nNo Previous Skills Or Experience Required. You can literally be a COMPLETE Newbie and Get RESULTS with just 5 minutes of actual “work”..\n\nSEE FULL REVIEW:   http://bit.ly/My_Traffic_Jacker\n\nKind Regards,\nCarmine Monahan\n\n\n\n\n\n");
INSERT INTO tbl_contactus VALUES("76","Veta Somers","veta.somers@gmail.com","My rimiqyt","You Need Leads, Sales, Conversions, Traffic for your site ?","Hello,\n \nMy name is Veta Somers, I want to know if:  You Need Leads, Sales, Conversions, Traffic for your site dkkkpmba.com  ?\n \nI will Find Leads that Buy From You ! \n\nI will Promote Your Business In Any Country To Any Niche !\n\nSEE FOR YOURSELF==>  http://bit.ly/Promote_Very_Efficiently\n \nDo not forget to read Review to convince you, is already being tested by many people who have trusted it !!\n \nKind Regards,\nVeta Somers \n\n\n\nUNSUBSCRIBE==>  http://bit.ly/Unsubscribe_Sales\n\n");
INSERT INTO tbl_contactus VALUES("77","Nicki Day","nicki.day@msn.com","Nzmwq mas ","NEW WAY to generate quick TRAFFIC and SALES in ANY niche with ZERO video/website creation, ZERO paid advertising/SEO.","Hello,\n \nTIRED OF WAITING FOREVER TO EARN A PROFIT ONLINE ?\n \nMy name is Nicki Day and I’m talking about a new way to generate quick traffic and sales in ANY niche with ZERO video/website creation, ZERO paid advertising/SEO. \n \nI’ve recently tried this product but quickly decide to write this review because I know this is exactly what you  are looking for your dkkkpmba.com \n \nNo Previous Skills Or Experience Required. You can literally be a COMPLETE Newbie and Get RESULTS with just 5 minutes of actual “work”..\n\nSEE FULL REVIEW:   https://is.gd/Nvs47l\n\nKind Regards,\nNicki Day\n\n\n\n\n\n");
INSERT INTO tbl_contactus VALUES("78","Katia Pigot","pigot.katia@gmail.com","Akhaa Zd U","Do not forget! Such Once a year!","Good Offer  http://bit.do/Big_Discount \n\nThe biggest sale of clothing, shoes, electronics, phones, auto, health and beauty products, products for children and adults, and much more\n\nPerfect Discount  https://cutt.us/Big_Discount");
INSERT INTO tbl_contactus VALUES("79","Noella Wicken","wicken.noella@yahoo.com","Aqzdcpi","Black Friday! Discount -70%","Do not forget! Such Once a year!\n\nBlack Friday! Discount -70%\n\nhttp://ali.pub/44pomr\n\n=======\nThe biggest sale of clothing, shoes, electronics, phones, auto, health and beauty products, products for children and adults, and much more\n=======\n\nhttp://ali.pub/44pomr");
INSERT INTO tbl_contactus VALUES("80","Ranji Dattatray Kumbhar","ranjitk4545@gmail.com","9881170934","Supply chain management","Plz contact me");
INSERT INTO tbl_contactus VALUES("81","Sunil","pawarsunilmim@gmail.com","7709457258","Test","Ok");
INSERT INTO tbl_contactus VALUES("82","Katherine Cline","cline@interactivewise.com","W Cy Kn Ai","Inquiry from Houston, TX","Inquiry from Houston, TX \n\nHello,\n\nDo you lack an extra stable income outside of your business or job?\n\nInteractivewise provides an opportunity that you can earn cash by sharing your opinion.\n\nNow take 5 minutes to fill out a survey, and you will see that $ 3 or $ 5 is credited to your account: https://www.interactivewise.com/cashsurvey\n\nCosts Nothing To Join.\n\nBest Regards,\nKatherine Cline\n\n*******************\nCompany: Interactivewise \nAddress: 11202 Clay Rd, Houston, TX 77041, United States\n\nUnsubscribe: https://www.interactivewise.com/unsubscribe");
INSERT INTO tbl_contactus VALUES("83","Mr.Sunil Pawar","pawarsunil222@gmail.com","7709457258","Admission Form ","rwetwetqweq");
INSERT INTO tbl_contactus VALUES("84","Ranjit Dattatray Kumbhar","ranjitk4545@gmail.com","9881170934","About admission","Sir I try to contact with you but our phone is not rechieble .plz call me back ..I want to take admission.\n");
INSERT INTO tbl_contactus VALUES("85","Santosh Kare","Santoshkare27@gmail.com","7709126105","Admission ","Want to know admission procedure, and fee structure also distance learning mode nature ");
INSERT INTO tbl_contactus VALUES("86","Priscilla Melrose","priscilla.melrose@msn.com","A Aiyjfco ","","Interested in advertising that costs less than $40 every month and sends tons of people who are ready to buy directly to your website? Visit: http://www.moreleadsandsales.xyz ");
INSERT INTO tbl_contactus VALUES("87","Valentin Trevascus","trevascus.valentin@gmail.com","Wwaa axvx","Whitehat SEO packages","hi there\n\nDo you want better ranks for your website?\n\nConsider a whitehat SEO plan and grab yourself the visibility that will get you more sales/leads\n\nMore info:\nhttps://www.ghostdigital.co/product-category/seo-packages/\n\nthanks and regards\nGhost Digital\n");
INSERT INTO tbl_contactus VALUES("88","Hildegard Bolden","bolden.hildegard@gmail.com","Tftmjqt bf","bolden.hildegard@gmail.com","Would you like to submit your business on thousands of advertising sites every month? One tiny investment every month will get you virtually unlimited traffic to your site forever! To find out more check out our site here: http://www.adblasting.xyz");
INSERT INTO tbl_contactus VALUES("89","Rachael Camarena","rachael.camarena65@outlook.com","U Jfmq","Increase local ranks with our package","hi there\nHope you are doing well and that everything is fine over there\n\nIf you`ll ever need a Local SEO boost for dkkkpmba.com, kindly consider our Local SEO plan, you wont be dissapointed\n\nMore details here:\nhttps://www.ghostdigital.co/product/local-seo-package/\n\nGmaps citations:\nhttps://www.ghostdigital.co/product/google-maps-citations/\n\n\nthanks and regards\nMikle\nghostdigital.mike@gmail.com\n\n");
INSERT INTO tbl_contactus VALUES("90","Aiden Pardey","aiden.pardey86@gmail.com","X G d p","aiden.pardey86@gmail.com","How would you like to submit your business on thousands of advertising sites monthly? Pay one low monthly fee and get virtually unlimited traffic to your site forever! For more information just visit: http://www.adblasting.xyz");
INSERT INTO tbl_contactus VALUES("91","Kaylee Dominguez","noreplymonkeydigital@gmail.com","Mh Geu Kry","Request for quotation","hi there\nAs per your inquiry, here is your unique domains backlinks package quotation and options for dkkkpmba.com\n\nhttps://www.arteseo.co/quotaion/\n\n\n\nthank you\nMikle\narteseo.co@gmail.com");
INSERT INTO tbl_contactus VALUES("92","Avery Cohen","team@israeltelemarketing.online","Mdkb Fd","American Sales & Telemarketing From Jerusalem","My company based out of Jerusalem and California, provides the highest quality American telemarketing and cold calling services.\n\nTo earn your business, we are offering significantly slashed prices for a trial/pilot period. Now is the time to try new lead generation tactics. \n\nEmail: team@israeltelemarketing.online\nWebsite: www.israeltelemarketing.online\n*Limited Time Offer/Some Restrictions Apply");
INSERT INTO tbl_contactus VALUES("93","Modesta List","list.modesta@hotmail.com","Izxlspzixe","","Do you need website, app, explanatory video, google local search engine optimization, search engine optimization and social media marketing. We are a US based company and serving our client since 1998. We guarantee your income will be doubled. Contact us immediately for FREE consultation?\nhttp://bit.ly/rapidmarketinginc or call us 1347-486-8238.");
INSERT INTO tbl_contactus VALUES("94","Adrianne Wyrick","adrianne.wyrick78@gmail.com","Ei Bwy","","Do you want to promote your website for free? Have a look at this: http://www.submityourfreeads.xyz");
INSERT INTO tbl_contactus VALUES("95","Janessa Winston","janessa.winston@gmail.com","Ccz Jwyb","","Absolutely No Charge traffic for your web page take a look at: http://www.freewebtraffic.xyz");
INSERT INTO tbl_contactus VALUES("96","Carina Isles","isles.carina@googlemail.com","L px yl","","Want more visitors for your website? Receive thousands of keyword targeted visitors directly to your site. Boost your profits fast. Start seeing results in as little as 48 hours. For additional information Check out: http://bit.ly/trafficmasters2020");
INSERT INTO tbl_contactus VALUES("97","Vilma Seiffert","seiffert.vilma@msn.com","W Dbf usfh","","Looking for fresh buyers? Receive hundreds of keyword targeted visitors directly to your site. Boost your profits super fast. Start seeing results in as little as 48 hours. For additional information Visit: http://www.trafficmasters.xyz");
INSERT INTO tbl_contactus VALUES("98","Brett Villarreal","brett.villarreal@gmail.com","Mwiqjanb l","","Want more visitors for your website? Receive hundreds of people who are ready to buy sent directly to your website. Boost your profits fast. Start seeing results in as little as 48 hours. For more info Visit: http://www.trafficmasters.xyz");
INSERT INTO tbl_contactus VALUES("99","Karol Quillen","quillen.karol14@gmail.com","Pjtlgi","","Absolutely Free web traffic for your website take a look at: https://bit.ly/unlimited-traffic-source");
INSERT INTO tbl_contactus VALUES("100","Henrietta Cunniff","cunniff.henrietta@hotmail.com","Tpmw x vjk","","In the past 15 years we have built over 400 websites and generated over 500,000 leads for our clients.\n\n \n\nWe are a US company – with tons of references, testimonials and happy clients – and we want to be your go to marketing agency!\n\n \n\nSo, here is our offer 15% off any of our services PLUS a FREE review of your:\n\n \n\n-Website (speed, SEO, look and feel, mobile compliance – everything)\n\n-Social media pages\n\n-Directory listings (are you showing up on google?  What about Alexa and Siri?)\n\n-Landing pages\n\n-Email newsletters\n\n-Even your promotional products and printed materials…!\n\n \n\nThe goal here is to make sure your brand is consistent – and your business grows!\n\nWe are offering a 15% off voucher for your business\n\n\nEmail me back with your contact information and website link at  DebbieSilver2112@gmail.com\n\n \n\nYou will not be sorry!\n\n \n\nRegards,\n\n \n\n \n\nDebbie Silver\n\nBranding & Marketing Specialist");
INSERT INTO tbl_contactus VALUES("101","Mike Saffern","mike@graphicdesignisrael.co","Lhvak","Shalom From Israel + Graphic Design Israel Intro","Shalom, Mike here.\n\nYour website and business look great and both seem well established.\n\nI am messaging you today to compliment your business + let you know about the unreasonably low pricing I am charging for a limited time to new clients interested in my graphic design services. \n\nReply back to say Hi, ask to see my portfolio, or check out my site. \n\nEmail me: Mike@graphicdesignisrael.co Website: GraphicDesignIsrael.co\n\n--\nMike Saffern\ngraphicdesignisrael.co\nMike@graphicdesignisrael.co");
INSERT INTO tbl_contactus VALUES("102","Caren Bobbitt","info@dkkkpmba.com","Xe Id Cmjd","Lead For dkkkpmba.com","Morning\n\nBuy N95 Face Mask and Medical Face Mask to protect your loved ones from the deadly CoronaVirus.  The price begins at $1.49 each.  If interested, please visit our site: thefacemask.online\n\nMany Thanks,\n\nContact Us - dkkkpmba.com");
INSERT INTO tbl_contactus VALUES("103","Eartha Teece","eartha.teece@hotmail.com","Qu Oi","","Greetings, I was just visiting your site and wondering about the payment method, which you use to accept credit card and local payments from your customers.\n\nI am working with WebPays (http://bit.ly/webpays) and we can serve your business by offering credit card and various local payment methods to accept online payments.\n\nThe best part part is that we price each business according to their activities, hence you could expect a better pricing to be offered to your business.\n\nIn general our pricing is 2.6% for credit card payments and 1.5% for local payments.\n\nIf you are interested or would like to see our quotes for your business, just provide us few details by the link: http://bit.ly/webpays-quote\n\nYou can also write me on info [at] webpays [dot] com.\n\nI will get back to with the pricing asap. Thanks.");
INSERT INTO tbl_contactus VALUES("104","Marla McPhee","noreply@monkeydigital.co","P thjtsf","Quality 500 web2 Article propreties","hi there\nBuy 500 web2 Articles backlinks, unique content, high DA Domains\nand increase Ranks and SEO value for dkkkpmba.com\n\nStart getting more leads and sales from your website\n\nYou can read more details about our service here\nhttps://www.monkeydigital.co/product/500-web2-0/\n\nthank you, stay safe\nMike\nMonkey Digital\nsupport@monkeydigital.co\n\n");
INSERT INTO tbl_contactus VALUES("105","Blondell Robe","blondell.robe@yahoo.com","Uidyqc","","Hello,\n\nWe have available the following, with low minimum order requirements - if you or anyone you know is in need:\n\n-3ply Disposable Masks\n-KN95 masks and N95 masks with FDA, CE certificate\n-Gloves\n-Disposable Gowns\n-Sanitizing Wipes\n-Hand Sanitizer\n-Face Shields\n-Oral and No Touch Thermometers\n-Swabs\n\nDetails:\n\nWe are based in the US\n\nAll products are produced in China\n\nWe are shipping out every day.\n\nMinimum order size varies by product\n\nWe can prepare container loads and ship via AIR or SEA.\n\nPlease reply back to debbiesilver2112@gmail.com with the product you need , the quantity needed, and the best contact phone number to call you\n\n\nThank you\n\nDebbie Silver\nPPE Product Specialist");
INSERT INTO tbl_contactus VALUES("106","Mary Wingo","mary.wingo@roxwellwaterhouse.com","Wqj j","Contact me if you are having supply troubles from China","Good afternoon---I am not sure who to contact, so if you could route this message into proper hands, I sure would appreciate it! \n\nI know that a lot of businesses heavily rely on shipments from all over the world in order to keep everything flowing. However, it appears that the gravity of the Coronavirus epidemic is curtailing shipments on millions of consumer products, with no end in sight. I am here to source crucial items needed so that you can keep your business running smoothly. \n\nMy name is Mary Wingo (native US citizen) and I can help you with supply and manufacturing from South America for the following sectors:\n\n-Building supplies, including paints and adhesive\n-Clothing, including uniforms, sports, underwear, hats, and shoes\n-Certain industrial materials\n-Plastics\n-Promotional and corporate gifts/awards\n-Ceramics\n-Fabric labeling and branding\n\nAnything else I can evaluate case by case.\n  \nI have carefully vetted local, family owned factories in person about these items to ensure deliverability and quality. These are items fully made locally, so there is no worry of supply chain disruption.\n\nI have been in the import/export business for 12 years and I believe that I can help you fill crucial gaps to help you keep things running. \n\nWhen would be a good time to continue this dialog further?\n\nMary Wingo\nUSA:+1-682-227-0100\nUSA +1-325-515-4103\nWhatsApp +593997072884\nSkype ID: maryiscontary13359 North Highway 183\nSuite 406-577\nAustin TX 78750\n");
INSERT INTO tbl_contactus VALUES("107","Richelle Chittenden","richelle.chittenden@googlemail.com","Yyzg qg","","Do you want more people to visit your website? Get hundreds of keyword targeted visitors directly to your site. Boost your profits fast. Start seeing results in as little as 48 hours. For additional information Check out: http://bit.ly/trafficmasters2020");
INSERT INTO tbl_contactus VALUES("108","Harold Grills","info@dkkkpmba.com","Yvkchmgdyn","Regarding dkkkpmba.com","Hello\n\nBuy N95 Face Mask and Medical Face Mask to protect your loved ones from the deadly CoronaVirus.  The price begins at $0.89 each.  If interested, please visit our site: pharmacyusa.online\n\nAll the best,\n\nContact Us - dkkkpmba.com");
INSERT INTO tbl_contactus VALUES("109","Deandre Lyons","deandre.lyons@outlook.com","Kkngs","Getting near-INSTANT traffic and earning passive commissions from OTHER people’s efforts has never been so easy for dkkkpmba.com","Hi there\n\nI’m talking about a new way to generate quick traffic and sales in ANY niche with ZERO video/website creation, ZERO paid advertising/SEO.\nI’ve recently tried this product but quickly decide to write this review because I know this is exactly what you guys are looking for.\n\nSO, HOW EXACTLY?\n\nWell, MyTrafficJacker allows users to search by keywords on either Wikipedia and YouTube and find LIVE, but EXPIRED links that are STILL posted on these sites that you can pick up for as little as $10 and redirect that traffic and authority ANYWHERE they’d like!\n\nMORE INFO HERE=>  https://bit.ly/2XsONxn\n\nKind Regards,\nDeandre Lyons ! Business Development Manager");
INSERT INTO tbl_contactus VALUES("110","Clay Brient","brient.clay@gmail.com","Jl Jc","Get Whole Foods $150 Giftcard now","would you like to get Whole Foods $150 Giftcard ? \nthis website now for limited time offer Whole Foods $150 Giftcard\nbut for USA visits only , \nhttp://lnkclik.com/8Nz1\npleas Not : if you are out side USA donot try because you will not get this offer \nthere is no proplem if you like to share this offer with your friends in USA	\nhttp://lnkclik.com/8Nz1\n");
INSERT INTO tbl_contactus VALUES("111","Reva Winfrey","reva.winfrey@msn.com","S xga us","You Want To Rank Your Videos On Top Within 48 Hours Or Less dkkkpmba.com","Hi\n\nDFY Suite is an established, high-quality social syndication system that allows you to get stunning content syndication \nfor your videos or niche sites WITHOUT having to do ANY of the work yourself.\n\n    +    There is NO software to download or install\n    +    There is NO account creation needed on your part\n    +    There is NO having to deal with proxies of captchas\n    +    There are NO complicated tutorials you have to watch\n\nDFY Suite 2 with more advanced features will become your powerful tool to serve the online marketing industry \nwhich gets more and more competitive. You will be able to skyrocket your business with very little effort.\n\nMORE INFO HERE=> https://bit.ly/3cUTynT");
INSERT INTO tbl_contactus VALUES("112","Dewey Vessels","dewey.vessels@gmail.com","Ydfqe","","How would you like to promote your website for free? Have a look at this: http://bit.ly/submityourfreeads");
INSERT INTO tbl_contactus VALUES("113","Amparo Elmer","office.largeglobes.com@gmail.com","Ivulmmk","Large world globes - Handmade Custom World Globes","Hello,\nOur company makes handmade Large world globes that can be customized for your brand, company or interior design https://bit.ly/www-largeglobes-com\nPlease let me know if you would be interested in a custom large world globe and we can send more information.\n\nThank you.\nBest regards,\nRemus Gall\nGlobemaker at www.largeglobes.com\nProject manager at Biodomes www.biodomes.eu\n+40 721 448 830\nSkype ID office@biodomes.eu\nStr. Vonhaz nr 2/a Carei, Romania\n\n-----------------------------\n\nclick to take your site off our list https://bit.ly/2yp4480");
INSERT INTO tbl_contactus VALUES("114","Rodolfo Glasfurd","noreply@arteseo.co","S z D k S","re: Your 6 months unlimited traffic Quote Request","here is your dkkkpmba.com 6 months traffic quote\nhttps://www.arteseo.co/unlimited-traffic/\n\n\n");
INSERT INTO tbl_contactus VALUES("115","Aretha Halford","aretha.halford@hotmail.com","Xmep I","","Secret way to advertise your website for TOTALLY FREE! See here: http://www.submityourfreeads.xyz");
INSERT INTO tbl_contactus VALUES("116","Eva Korner","korner.eva@outlook.com","Rwiwj Pvl","","Looking for fresh buyers? Receive thousands of keyword targeted visitors directly to your site. Boost revenues quick. Start seeing results in as little as 48 hours. To get info Check out: http://www.trafficmasters.xyz\n\n");
INSERT INTO tbl_contactus VALUES("117","Aurelio Champion","champion.aurelio@gmail.com","Xm ockyig","You Want To Rank Your Videos On Top Within 48 Hours Or Less dkkkpmba.com","Good day\n\nDFY Suite is an established, high-quality social syndication system that allows you to get stunning content syndication \nfor your videos or niche sites WITHOUT having to do ANY of the work yourself.\n\n    +    There is NO software to download or install\n    +    There is NO account creation needed on your part\n    +    There is NO having to deal with proxies of captchas\n    +    There are NO complicated tutorials you have to watch\n\nDFY Suite 2 with more advanced features will become your powerful tool to serve the online marketing industry \nwhich gets more and more competitive. You will be able to skyrocket your business with very little effort.\n\nMORE INFO HERE=> https://bit.ly/3fabhtt");
INSERT INTO tbl_contactus VALUES("118","Claribel Ryland","claribel.ryland@yahoo.com","Bfnsp Kb h","You Want To Rank Your Videos On Top Within 48 Hours Or Less dkkkpmba.com","Hi there\n\nDFY Suite is an established, high-quality social syndication system that allows you to get stunning content syndication \nfor your videos or niche sites WITHOUT having to do ANY of the work yourself.\n\n    +    There is NO software to download or install\n    +    There is NO account creation needed on your part\n    +    There is NO having to deal with proxies of captchas\n    +    There are NO complicated tutorials you have to watch\n\nDFY Suite 2 with more advanced features will become your powerful tool to serve the online marketing industry \nwhich gets more and more competitive. You will be able to skyrocket your business with very little effort.\n\nMORE INFO HERE=> https://bit.ly/2YsC3aq");
INSERT INTO tbl_contactus VALUES("119","Tanisha Bunbury","tanisha.bunbury@hotmail.com","Bdulv","You Want To Rank Your Videos On Top Within 48 Hours Or Less dkkkpmba.com","Good day\n\nDFY Suite is an established, high-quality social syndication system that allows you to get stunning content syndication \nfor your videos or niche sites WITHOUT having to do ANY of the work yourself.\n\n    +    There is NO software to download or install\n    +    There is NO account creation needed on your part\n    +    There is NO having to deal with proxies of captchas\n    +    There are NO complicated tutorials you have to watch\n\nDFY Suite 2 with more advanced features will become your powerful tool to serve the online marketing industry \nwhich gets more and more competitive. You will be able to skyrocket your business with very little effort.\n\nMORE INFO HERE=> https://bit.ly/2WjU48k");
INSERT INTO tbl_contactus VALUES("120","Heath Creech","creech.heath9@gmail.com","R iju","","TRIFECTA! A novel that starches your emotional – erotic itch!\nAgainst a background of big business, deceit, frustration, oppression drives a wide range of emotions as three generations of women from the same family, turn to the same man for emotional support and physical gratification!\nA wife deceives her husband while searching for her true sexuality!\nWhat motivates the wife’s mother and son-in-law to enter into a relationship?\nThe wife’s collage age daughter, with tender guidance from her step-father, achieves fulfillment!\nDoes this describe a dysfunctional family? Or is this unspoken social issues of modern society?\nBLOCKBUSTER Opening! A foursome of two pair of lesbians playing golf. A little hanky – panky, while searching for a lost ball out of bounds. Trifecta has more turns and twist than our intestines.\nTrifecta! Combination of my personal experiences and creativity.\nhttps://bit.ly/www-popejim-com for “CLICK & VIEW” VIDEO. Send me your commits.\nAvailable amazon, book retailers.\nTrifecta! by James Pope");
INSERT INTO tbl_contactus VALUES("121","Shubham sanjay Rananavare","shubhamrananavare9@gmail.com","9881480105","mba admission","About MBA admission information");
INSERT INTO tbl_contactus VALUES("122","Hermine Searcy","searcy.hermine@outlook.com","Yy Rsudw U","searcy.hermine@outlook.com","Want to promote your business on thousands of online ad websites every month? For a small monthly payment you can get almost endless traffic to your site forever!\n\nTake a look at: https://bit.ly/rapid-ads");
INSERT INTO tbl_contactus VALUES("123","Muoi Snider","muoi.snider@msn.com","Idjaragtzy","The Lockdown Formula – A Vaccine For Your Financial Health for dkkkpmba.com","Hi there\n\nThe Lockdown Formula is a breakthrough system that allows you to learn how to quickly make money online \nusing affiliate marketing and using a simple-to-set-up system with basic squeeze pages that take people to an offer. \nEspecially, it also offers you full traffic generation training.\n\nMORE INFO HERE=>  https://bit.ly/2xKKLpA\n\n");
INSERT INTO tbl_contactus VALUES("124","Kaylene Pettis","pettis.kaylene@msn.com","D flzd","","Want more visitors for your website? Get thousands of people who are ready to buy sent directly to your website. Boost revenues super fast. Start seeing results in as little as 48 hours. For additional information Visit: https://bit.ly/buy-web-traffic\n\n");
INSERT INTO tbl_contactus VALUES("125","Rich Michelides","michelides.rich@gmail.com","Hw Kppt","","Interested in the latest fitness , wellness, nutrition trends?\n\nCheck out my blog here: https://bit.ly/www-fitnessismystatussymbol-com\n\nAnd my Instagram page @ziptofitness");
INSERT INTO tbl_contactus VALUES("126","Harold Schaaf","harold.schaaf@gmail.com","Exsg","","ABOLISH REACTIVE DEPRESSION AND EMERGE FROM ITS DEEP, DARK, BLACK HOLE?\n• Do you feel this came from the beginnings of a dysfunctional family system?\n• Or did this come from the loss of a beloved job or loved one?\n• Or did this come from dire effects from the disease of Alcoholism?\n• Or did this come from the brainwashing attempts of a fearful and angry world, i.e. terroristic recruitment?\nDo you know that whatever caused this DEEP, DARK, BLACK HOLE OF DEPRESSION which may have come from a NERVOUS BREAKDOWN can cease its influence over your life? Yes, you do not have to live buried in negative thinking from the defeat from negative life experiences in your life. Please know that any tragic experiences from childhood to adulthood need no longer affect your chance to gain emotional wellbeing.\nInstead, now you have the opportunity to be HAPPY and in PEACEFUL CONTROL OF YOUR OWN DESTINY with only the memory of what once ailed you. Now is the time to overcome depression and begin to take control over your life. Not only that, you alone have the opportunity to reverse negative thinking and achieve your very own POSITIVE BELIEF SYSTEM.\nPLEASE NOTE: Your views on spirituality or religion will not prevent you from successfully implementing your own PARENTAL SELF-LOVE PROCESS to ACHIEVE PURPOSE, MOTIVATION, GOOD SELF-ESTEEM, SUCCESS, AND MORE. Yes, like Lin Tillman did, you too can ACHIEVE MORE THAN YOU ASKED FOR and make meaningful and healthy contributions to this planet.\nYou can learn more about Lin’s journey in her book The Invisible Girl & GOD, where she shares her TRUE STORY of how she healed herself from an agonizing depression with suicidal ideations.\nGO TO: https://bit.ly/Depression-self-help to learn more");
INSERT INTO tbl_contactus VALUES("127","Kris Richter","no-reply@digitalsy.org.uk","N Cbm","Customized Monthly SEO plans","Hello\n\nThis is Mike Thimmig from DIGITALSY \n\nWhile checking your dkkkpmba.com, which by the way looks awesome, I`ve seen that the organic search section of it could be improved a lot.\nWe will help you succeed, while making your organic visibility increase progressively each month.\n\nCheck more details about our Customized monthly SEO plans here\nhttps://digitalsy.org.uk/seo-pricing/\n\nthank you\nMike Thimmig\nhttps://digitalsy.org.uk/\nsupport@digitalsy.org.uk\n");
INSERT INTO tbl_contactus VALUES("128","Mr.Sunil Pawar","pawarsunilmim@gmail.com","7709457258","Admission Form ","trjkfdfgtr");
INSERT INTO tbl_contactus VALUES("129","Sharon Wheatley","sharon.wheatley@gmail.com","Gi bldmgii","","Hello,\nWe are a great team from Palma de Mallorca (Spain) who are offering gorgeous holiday houses for rent, at special prices.\nWe offer large experience in the field- more than 15 years , high quality services, 24h assistance and speaking languages like Spanish, English and German.\nThis could be the vacation of your dream that is what you deserve this year, therefore you will find the best offers of absolutely beautiful villas in the island just visiting our website https://bit.ly/mysunshinetravel and feel free to contact us, via phone or email.\nSee you soon!");
INSERT INTO tbl_contactus VALUES("130","Mr.Sunil Pawar","pawarsunilmim@gmail.com","8888330843","Admission Form","ok");
INSERT INTO tbl_contactus VALUES("131","566","kbg@gamil.com","46598","uih87u","64l");
INSERT INTO tbl_contactus VALUES("132","Sherri Saucedo","sherri.saucedo@msn.com","Xwf s","","How would you like to have no charge advertising for your website? Check out: https://bit.ly/zero-cost-ads");
INSERT INTO tbl_contactus VALUES("133","Jonelle Noel","jonelle.noel@gmail.com","Pzpxmauy f","","EROTICA becomes REALITY!!!\nStepping Stones to the ARCH De Pleasure\n     Men, put your feet in James Pope’s shoes, women put your feet in the women’s shoes I encounter, as I traveled the road from farm-to-MATTRESONAME!\nStepping Stones is my third novel in a 3, connected, series.  1- Post Hole Digger! 2-Trifecta! \nhttps://bit.ly/www-popejim-com “CLICK & VIEW videos.  Search: amazon.com, title - author");
INSERT INTO tbl_contactus VALUES("134","SIDDIQUI M A M S ","masajju143@gmail.com","8087158412","MBA admission","MBA Admission needed");
INSERT INTO tbl_contactus VALUES("135","SIDDIQUI M A M S ","masajju143@gmail.com","8087158412","MBA admission","MBA Admission needed");
INSERT INTO tbl_contactus VALUES("136","SIDDIQUI M A M S ","masajju143@gmail.com","8087158412","MBA admission","MBA Admission needed");
INSERT INTO tbl_contactus VALUES("137","Rushikesh mane","rushikeshmane8384@gmail.com","9960538384","Mba art","I want information about MBA");
INSERT INTO tbl_contactus VALUES("138","Eve Brooks","eve@explainthebusiness.com","Ld jpaxjdi","We have made Explainer videos in your industry","Hey, I messaged previously about how explainer videos became an absolute must for every website in 2020. \n\nMy team has created dozens of videos for real estate brokers, investors, and many other relevant industries, and our clients see amazing results from these productions.\n\nAs you know, Google is constantly changing its SEO algorithm. The only thing that has remained consistent is that adding an explainer video increases website rank and most importantly keeps customers on your page for longer, increasing conversions ratios.\n\nMy team has created thousands of marketing videos including dozens in your field. Simplify your pitch, increase website traffic, and close more business.\n\nShould I send over some industry-specific samples?\n\n-- Eve Brooks\n\nEmail: eve@explainthebusiness.com\nWebsite: http://explainthebusiness.com\n\n");
INSERT INTO tbl_contactus VALUES("139","Mr.Sunil Pawar","ramchandramadane495@gmail.com","8888330843","Admission Form","zvdfb");
INSERT INTO tbl_contactus VALUES("140","Lacy Dacre","lacy.dacre@gmail.com","Dthnf","","Stem cell therapy has proven itself to be one of the most effective treatments for COPD (Chronic Obstructive Pulmonary Disorder). IMC is the leader in stem cell therapies in Mexico. For more information on how we can treat COPD please visit:\nhttps://bit.ly/copd-integramedicalcenter");
INSERT INTO tbl_contactus VALUES("141","Malissa Landale","malissa.landale23@gmail.com","Mmasot","","Do you want to promote your website for free? Have a look at this: http://www.free-ad-posting.xyz");
INSERT INTO tbl_contactus VALUES("142","Jim Cochran","jim.cochran@outlook.com","Aefhb cupi","","Looking for fresh buyers? Get thousands of keyword targeted visitors directly to your site. Boost revenues fast. Start seeing results in as little as 48 hours. To get info Check out: http://www.getwebsitevisitors.xyz\n");
INSERT INTO tbl_contactus VALUES("143","Jean Frantz","frantz.jean13@gmail.com","Yaww xhtni","","TITLE: Are YOU Building Your Own DREAMS Or Has SOMEONE ELSE Hired You To Build THEIRS? \n\nDESCRIPTION: Have you ever looked at sites like Google or Facebook and asked yourself…“How can they make SO MUCH MONEY when they aren’t even really selling any products?!?!”\nWell, Google and Facebook are cashing in on their platforms. They’re taking advantage of the millions of people who come to their sites…Then view and click the ads on their pages.\nThose sites have turned into billion dollar companies by getting paid to send traffic to businesses. \n\nDid You Know That More People Have Become Millionaires In The Past Year Than Ever Before? Did You Know You Can Make Money By Becoming A Traffic Affiliate?\n\nWatch Our Video & Discover The Easy 1-Step System Our Members Are Using To Get Paid Daily.\n\nURL: https://bit.ly/retirement-biz\n");
INSERT INTO tbl_contactus VALUES("144","Ervin Upshaw","info@dkkkpmba.com","Rczb N","Concerning dkkkpmba.com","Be Free from Neck Pain\nTry NeckFlexer & Relieve Neck Pain Effortlessly In 10 Min!\nSave 50% OFF + FREE Worldwide Shipping\n\nShop Now: neckflexer.online\n\n✅ Designed By Doctor & Chiropractor\n✅ Ergonomic Design - Fits Everyone\n✅ Circulation To Head\n✅ Stimulating Key Result Area\n\nSincerely,\n\nContact Us - dkkkpmba.com");
INSERT INTO tbl_contactus VALUES("145","Anne Shurtleff","anne.shurtleff68@gmail.com","L Cakmg","","Greetings, are you 100% confident your sales team has the skills to consistently close busines?  If not, 2020 could cripple your company’s growth for years to come!  Now you can give your team the skills to rise above the competition, overcome objections, negotiate better margins, and close more deals.  We offer customized sales training through live webinars or onsite sessions.  Let’s chat for 15 minutes and I can show you how you can increase sales and closing rates by 15-20% in the next 90 days.  Email me and let me know a time that works for you:  john@stridehigher.com or call 800-850-8979.");
INSERT INTO tbl_contactus VALUES("146","Willa McBeath","noreplymonkeydigital@gmai.com","Atwsuci","NEW: Rare DA 50+ backlinks","Get backlinks from websites which have Domain Authority above 50. Very rare and hard to get backlinks. Order today at a very low price, while the offer lasts.\n\nread more:\nhttps://www.monkeydigital.co/product/250-da-50-backlinks/\n\nthanks and regards\nMonkey Digital Team\nsupport@monkeydigital.co");
INSERT INTO tbl_contactus VALUES("147","Robyn Coats","info@dkkkpmba.com","H Fdm","Re: dkkkpmba.com","Good Morning\n\nWear with intent, live with purpose. Fairly priced sunglasses with high quality UV400 lenses protection.  Free Worldwide Shipping.\n\nOrder here: kickshades.online\n\nThanks and Best Regards,\n\nContact Us - dkkkpmba.com");
INSERT INTO tbl_contactus VALUES("148","Sharyn Buckland","sharyn.buckland45@hotmail.com","U Fkcmrhnu","MUST-READ If You’ve Got A Website","Hi,\n\nDo you have a Website? Of course you do because I am looking at your website dkkkpmba.com now.\n\nAre you struggling for Leads and Sales?\n\nYou’re not the only one.\n\nSo many Website owners struggle to convert their Visitors into Leads & Sales.\n\nThere’s a simple way to fix this problem.\n\nYou could use a Live Chat app on your Website dkkkpmba.com and hire Chat Agents.\n\nBut only if you’ve got deep pockets and you’re happy to fork out THOUSANDS of dollars for the quality you need.\n\n=====\n\nBut what if you could automate Live Chat so it’s HUMAN-FREE?\n\nWhat if you could exploit NEW “AI” Technology to engage with your Visitors INSTANTLY.\n\nAnd AUTOMATICALLY convert them into Leads & Sales.\n\nWITHOUT spending THOUSANDS of dollars on Live Chat Agents.\n\nAnd WITHOUT hiring expensive coders.\n\nIn fact, all you need to do to activate this LATEST “AI” Website Tech..\n\n..is to COPY & PASTE a single line of “Website Code”.\n\n==> http://www.zoomsoft.net/ConversioBot\n\n======\n\nJoin HUGE Fortune 500 companies like:\n\nFacebook Spotify Starbucks Staples The Wall Street Journal Pizza Hut Amtrak Disney H&M & Mastercard\n\nThey all use similar “AI” Chat Technology to ConversioBot - the Internet’s #1 Chatbot for Website Owners.\n\nThe founders of ConversioBot have used their highly sophisticated ChatBot to:\n\n- AUTOMATICALLY build a massive Email List of 11,643 Subscribers in just 7 Days\n\n- AUTOMATICALLY add 6,386 Sales in only 6 Months\n\n- AUTOMATICALLY explode their Conversion Rate by 198% in only 6 Hours.\n\n=====\n\nNow it’s your turn to get in on this exciting NEW Cloud-Based App.\n\nYou can start using ConversioBot today by copying and pasting ONE line of “Automated Bot Code\" to your Website.\n\nWatch this short video to find out how >> http://www.zoomsoft.net/ConversioBot\n\nRegards,\n\nConversioBot Team\n\nP.S. This “AI” Technology works with: - Affiliate Review Sites - List-Building Pages - WordPress Blogs (it comes with a Plugin) - Sales Letters - eCommerce Websites - Local Business Sites - Webinar Registration Pages - Consultancy Websites - Freelance Websites\n\nAlmost ANY Website you can think of..\n\n==> This could be happening on your Website TODAY.. http://www.zoomsoft.net/ConversioBot\n\nUNSUBSCRIBE http://www.zoomsoft.net/unsubscribe");
INSERT INTO tbl_contactus VALUES("149","Bette Tweddle","info@dkkkpmba.com","Kxzdmcd i ","dkkkpmba.com","Hi\n\nDefrost frozen foods in minutes safely and naturally with our THAW KING™. \n\n50% OFF for the next 24 Hours ONLY + FREE Worldwide Shipping for a LIMITED time\n\nBuy now: thawking.online\n\nBest regards,\n\nContact Us");
INSERT INTO tbl_contactus VALUES("150","Karen Luevano","luevano.karen@msn.com","Zh W F","","Do you want more people to visit your website? Get thousands of keyword targeted visitors directly to your site. Boost revenues super fast. Start seeing results in as little as 48 hours. To get details Check out: https://bit.ly/more-website-visits\n\n");
INSERT INTO tbl_contactus VALUES("151","Mauricio Cook","cook.mauricio@googlemail.com","Xfol","Text To Speech In 3 Clicks for dkkkpmba.com","Hi there,\n\nAre You Using Videos to Turn dkkkpmba.com Website Traffic into Leads???\n\nIf a picture is worth a thousand words, a product video could very well be worth a thousand sales. Considering that video now appears in 70% of the top 100 search results listings, and that viewers are anywhere from 64-85% more likely to buy after watching a product video – this is one marketing force you can’t afford to ignore. Here’s why:\n\nOnline video marketing has finally come of age. We no longer have to deal with a glut of sluggish connections, incompatible technologies or bland commercials begging for our business. These days, smart companies and innovative entrepreneurs are turning the online broadcast medium into a communications cornucopia: a two-way street of give-and-take.\n\nHow Well Does Online Video Convert?\nThe great thing about online video is that people vastly prefer watching over reading (just consider the last time you watched the news versus reading a newspaper!) It spans nearly every industry and demographic. \n\nYou know that few things are more annoying. when watching a video,,,\nthan a terrible audio track – tinny sounding, bad volume and you struggle to get what is being said…\nBut even WORSE! Text To Speech!\n\nThose terrible Text To Speech audios on videos that sound…\nFake, emotionless, robotic and cheap!\nThat makes me hit the Back Button every time\n\nSo what to do if we don’t have a nice voice for our own or our clients videos?\nWe pay somebody to do it for us, and that ain’t cheap! There was no real alternative…\nUNTIL NOW!\n\n> http://www.zoomsoft.net/Text2Speach\n\nSpeechelo is the incredible new Text To Speech software that actually sounds like Real People\nwith pauses, tone, inflection – so much so that you are hard put to tell that it’s not a Real Person.\n\nIn just a few clicks you can have natural sounding Voice-overs for your videos.\n\nIt’s available at an incredible low price if you are quick.\nJust listen to the app, in action in the Sales video on the page…\n\n> http://www.zoomsoft.net/Text2Speach\n\n\nIf you would like to stop future emails, http://www.zoomsoft.net/unsubscribe\n");
INSERT INTO tbl_contactus VALUES("152","Felix Funderburk","funderburk.felix31@gmail.com","K Voa e fc","cheap monthly SEO plans","hi there\nI have just checked dkkkpmba.com for the ranking keywords and seen that your SEO metrics could use a boost.\n\nWe will improve your SEO metrics and ranks organically and safely, using only whitehat methods, while providing monthly reports and outstanding support.\n\nPlease check our pricelist here, we offer SEO at cheap rates. \nhttps://www.hilkom-digital.de/cheap-seo-packages/\n\nStart increasing your sales and leads with us, today!\n\nBe safe and best regards\n\nMike\nHilkom Digital Team\nsupport@hilkom-digital.de");
INSERT INTO tbl_contactus VALUES("153","Zachary Sloman","sloman.zachary@gmail.com","C Sozs","","The Live Wire Network Show is a syndicated Network which is broadcast around the United Kingdom and global areas,\nincorporating FM, DAB, AM and Digital Radio Stations.\n\nSteve Osborne Media was established in 1989 for the sole purpose  of promoting your business and products to a larger audience.\n\nThese campaigns include celebrity interviews, lifestyle, business, entertainment, film, fashion, food, music and much more.\n\nWe currently run Live Wire Today which is a feature led podcast (on various topics) which consists of an interview with one of \nour established presenters and the media package will be sent to podcast sites which includes Apple, iTunes,Facebook and Twitter.\n\nIn addition we will provide you with a download link so the podcast can be used for personal websites and social media accounts.\n\nIf you would like more information in the first instance please contact us via our website https://bit.ly/steveosborne\n\nEmail: steveosbornemedia@mail.com");
INSERT INTO tbl_contactus VALUES("154","Dorcas Lehmann","dorcas.lehmann@gmail.com","W Ec o","","Do you want no cost advertising for your website? Check out: https://bit.ly/no-cost-ads");
INSERT INTO tbl_contactus VALUES("155","1","arachni@email.gr","1","1","1");
INSERT INTO tbl_contactus VALUES("156","","","","","");
INSERT INTO tbl_contactus VALUES("157","1","arachni@email.gr","1","1","1)");
INSERT INTO tbl_contactus VALUES("158","1","arachni@email.gr","1","1","1");
INSERT INTO tbl_contactus VALUES("159","1)","arachni@email.gr","1","1","1");
INSERT INTO tbl_contactus VALUES("160","1","arachni@email.gr","1)","1","1");
INSERT INTO tbl_contactus VALUES("161","1","arachni@email.gr)","1","1","1");
INSERT INTO tbl_contactus VALUES("162","1","arachni@email.gr","1","1","1");
INSERT INTO tbl_contactus VALUES("163","1","arachni@email.gr","1","1)","1");
INSERT INTO tbl_contactus VALUES("164","Manie Zoll","manie.zoll@gmail.com","Fmfzswzade","","No cost advertising for your website here: http://www.zero-cost-forever-ads.xyz");
INSERT INTO tbl_contactus VALUES("165","Tam Tyree","tam.tyree96@msn.com","Le mgj","","Is your company fully virtual yet? Corona has changed the World; use the Engajer platform to improve your marketing, sales, and customer support. Normally thousands of dollars, now reduced down to two plans of $49 / mo or $150 / mo for the next 1,000 signups. Signup here: https://bit.ly/engajer-pricing");
INSERT INTO tbl_contactus VALUES("166","Erica Woodley","woodley.erica20@gmail.com","I bqzlhbsf","","Would you be interested in advertising that charges less than $40 per month and delivers hundreds of people who are ready to buy directly to your website? For details visit: http://www.getwebsitevisitors.xyz ");
INSERT INTO tbl_contactus VALUES("167","Darell Ruyle","ruyle.darell@gmail.com","Na E i","cheap monthly SEO plans","hi there\nI have just checked dkkkpmba.com for the ranking keywords and seen that your SEO metrics could use a boost.\n\nWe will improve your SEO metrics and ranks organically and safely, using only whitehat methods, while providing monthly reports and outstanding support.\n\nPlease check our pricelist here, we offer SEO at cheap rates. \nhttps://www.hilkom-digital.de/cheap-seo-packages/\n\nStart increasing your sales and leads with us, today!\n\nBe safe and best regards\n\nMike\nHilkom Digital Team\nsupport@hilkom-digital.de");
INSERT INTO tbl_contactus VALUES("168","khule rushikesh","rushikhule143@gmail.com","7028447751","MBA","what is the fee structure of MBA. ");
INSERT INTO tbl_contactus VALUES("169","Silas Cushman","cushman.silas@outlook.com","Bcs Arhi","You Have Been Called Upon","Hello, I have been informed to contact you. The CIA has been doing intensive research for the past fifty years researching on what we call so called life. That information has been collected and presented for you here https://cutt.ly/cfgu7Vw This has been the finding as of seventeen years ago as of today. Now governments and other large organizations have develop technology around these concepts for their own deceptive uses. Soon you will be contacted by other means for counter measures and the part that you play in all this. Please get this as soon as possible because there are powers that be to take down this information about this.");
INSERT INTO tbl_contactus VALUES("170","Chang Pettiford","pettiford.chang@gmail.com","Vros ov","","Hello, I was just on your site and submitted this message via your contact form. The \"contact us\" page on your site sends you these messages to your email account which is the reason you are reading my message right now right? This is the holy grail with any type of advertising, getting people to actually READ your advertisement and I did that just now with you! If you have an advertisement you would like to blast out to millions of websites via their contact forms in the U.S. or to any country worldwide let me know, I can even target your required niches and my charges are very affordable. Reply here: kinleytrey96@gmail.com\n\nreport abuse here https://bit.ly/2yp4480");
INSERT INTO tbl_contactus VALUES("171","Louanne Yocum","louanne.yocum71@msn.com","Ofw Ue t c","louanne.yocum71@msn.com","\nTired of paying for clicks and getting lousy results? Now you can post your ad on thousands of advertising websites and you only have to pay a single monthly fee. These ads stay up forever, this is a continual supply of organic visitors! \n\nFor details check out: https://bit.ly/free-traffic-always");
INSERT INTO tbl_contactus VALUES("172","Brenda Gruenewald","gruenewald.brenda@yahoo.com","L Rsr","I WILL FIND POTENTIAL CUSTOMERS FOR YOU","I WILL FIND POTENTIAL CUSTOMERS FOR YOU\n  \nI’m talking about a better promotion method than all that exists on the market right now, even better than email marketing.\nJust like you received this message from me, this is exactly how you can promote your business or product.\n\nCLAIM YOUR FREE TEST =>  https://bit.ly/3lr6nLV");
INSERT INTO tbl_contactus VALUES("173","Ursula Alderman","ursula.alderman@gmail.com","Opdkscc Sz","","Do you want more people to visit your website? Receive tons of people who are ready to buy sent directly to your website. Boost revenues quick. Start seeing results in as little as 48 hours. To get details Check out: http://bit.ly/buy-website-visitors");
INSERT INTO tbl_contactus VALUES("174","Stephanie Collits","stephanie.collits16@msn.com","D nkjrq","","Secret way to advertise your website for TOTALLY FREE! See here: http://www.completely-free-ad-posting.xyz");
INSERT INTO tbl_contactus VALUES("175","Tara Mireles","mireles.tara46@yahoo.com","Aw sw bn","I WILL FIND POTENTIAL CUSTOMERS FOR YOU","I WILL FIND POTENTIAL CUSTOMERS FOR YOU\n  \nI’m talking about a better promotion method than all that exists on the market right now, even better than email marketing.\nJust like you received this message from me, this is exactly how you can promote your business or product.\n\nCLAIM YOUR FREE TEST (Contact me)\nSkype ID  : (live:.cid.5554a4758747b4a5)\nEmail: (ventfara@mail.com)");
INSERT INTO tbl_contactus VALUES("176","Minnie Kendall","support@hyperlabs.co","Wqutl fznh","website traffic quote request","hi there\nhere is the your quote on the Country targeted organic website traffic:\n\nhttps://hyperlabs.co/quote/\n\nthanks and regards\nMike\nHyperlabs LTF\n\n");
INSERT INTO tbl_contactus VALUES("177","Rashad Gascoigne","rashad.gascoigne@outlook.com","Sgbjmad en","I WILL FIND POTENTIAL CUSTOMERS FOR YOU","I WILL FIND POTENTIAL CUSTOMERS FOR YOU\n  \nI’m talking about a better promotion method than all that exists on the market right now, even better than email marketing.\nJust like you received this message from me, this is exactly how you can promote your business or product.\n\nCLAIM YOUR FREE TEST (Contact me)\nSkype ID  : (live:.cid.5554a4758747b4a5)\nEmail: (ventfara@mail.com)");
INSERT INTO tbl_contactus VALUES("178","Joe Miller","info@domainworld.com","HMU30","VTYST","IMPORTANCE NOTICE\n\nNotice#: 491343\nDate: 2020-09-23    \n\nExpiration message of your dkkkpmba.com\n\nEXPIRATION NOTIFICATION\n\nCLICK HERE FOR SECURE ONLINE PAYMENT: https://godomainser.com/?n=dkkkpmba.com&r=a&t=1600759464&p=v1\n\nThis purchase expiration notification dkkkpmba.com advises you about the submission expiration of domain dkkkpmba.com for your e-book submission. \nThe information in this purchase expiration notification dkkkpmba.com may contains CONFIDENTIAL AND/OR LEGALLY PRIVILEGED INFORMATION from the processing department from the processing department to purchase our e-book submission. NON-COMPLETION of your submission by the given expiration date may result in CANCELLATION of the purchase.\n\nCLICK HERE FOR SECURE ONLINE PAYMENT: https://godomainser.com/?n=dkkkpmba.com&r=a&t=1600759464&p=v1\n\nACT IMMEDIATELY. The submission notification dkkkpmba.com for your e-book will EXPIRE WITHIN 2 DAYS after reception of this email\n\nThis notification is intended only for the use of the individual(s) having received this message. \n\nPLEASE CLICK ON SECURE ONLINE PAYMENT TO COMPLETE YOUR PAYMENT\n\nSECURE ONLINE PAYMENT: https://godomainser.com/?n=dkkkpmba.com&r=a&t=1600759464&p=v1\n\nNon-completion of your submission by given expiration date may result in cancellation.\n\nAll online services will be restored automatically upon confirmation of payment. Delivery will be completed within 24 hours. \n\nCLICK UNDERNEATH FOR IMMEDIATE PAYMENT:\n\nSECURE ONLINE PAYMENT: https://godomainser.com/?n=dkkkpmba.com&r=a&t=1600759464&p=v1");
INSERT INTO tbl_contactus VALUES("179","Jyoti Todkar","todkarjyoti@gmail.com","9049463656","TC/LC Required","I was a student of batch 2009-11, i have  successfully completed my MBA course and required my TC/LC for further education. Request you to provide my the concerned persons contact number to talk in regards. I am trying to contact you through the contact number given on the website.");
INSERT INTO tbl_contactus VALUES("180","Michelle Akin","michelle.akin@outlook.com","Vuofm","I WILL FIND POTENTIAL CUSTOMERS FOR YOU","I WILL FIND POTENTIAL CUSTOMERS FOR YOU\n  \nI’m talking about a better promotion method than all that exists on the market right now, even better than email marketing.\nJust like you received this message from me, this is exactly how you can promote your business or product.\nSEE MORE =>  https://bit.ly/3lr6nLV");
INSERT INTO tbl_contactus VALUES("181","NUtdyeHOF","extrapreatcn@gmail.com","FaEHuhfo","UEStyCDbFViZYmM","exAqXkBvSty");
INSERT INTO tbl_contactus VALUES("182","wdoXGSikjMc","extrapreatcn@gmail.com","QpWveGRZqg","OUBmwYpbsE","xrAMHaqDFNCw");
INSERT INTO tbl_contactus VALUES("183","Leopoldo Frias","leopoldo.frias@hotmail.com","Vyxwqpwwp","","Would you like no cost advertising for your website? Check out: http://bit.ly/post-free-ads-here");
INSERT INTO tbl_contactus VALUES("184","Joe Miller","info@domainworld.com","KIUILWF","N5PZWR8","IMPORTANCE NOTICE\n\nNotice#: 491343\nDate: 2020-10-05    \n\nExpiration message of your dkkkpmba.com\n\nEXPIRATION NOTIFICATION\n\nCLICK HERE FOR SECURE ONLINE PAYMENT: http://gosafemydomain.com/?n=dkkkpmba.com&r=a&t=1601818742&p=v1\n\nThis purchase expiration notification dkkkpmba.com advises you about the submission expiration of domain dkkkpmba.com for your e-book submission. \nThe information in this purchase expiration notification dkkkpmba.com may contains CONFIDENTIAL AND/OR LEGALLY PRIVILEGED INFORMATION from the processing department from the processing department to purchase our e-book submission. NON-COMPLETION of your submission by the given expiration date may result in CANCELLATION of the purchase.\n\nCLICK HERE FOR SECURE ONLINE PAYMENT: http://gosafemydomain.com/?n=dkkkpmba.com&r=a&t=1601818742&p=v1\n\nACT IMMEDIATELY. The submission notification dkkkpmba.com for your e-book will EXPIRE WITHIN 2 DAYS after reception of this email\n\nThis notification is intended only for the use of the individual(s) having received this message. \n\nPLEASE CLICK ON SECURE ONLINE PAYMENT TO COMPLETE YOUR PAYMENT\n\nSECURE ONLINE PAYMENT: http://gosafemydomain.com/?n=dkkkpmba.com&r=a&t=1601818742&p=v1\n\nNon-completion of your submission by given expiration date may result in cancellation.\n\nAll online services will be restored automatically upon confirmation of payment. Delivery will be completed within 24 hours. \n\nCLICK UNDERNEATH FOR IMMEDIATE PAYMENT:\n\nSECURE ONLINE PAYMENT: http://gosafemydomain.com/?n=dkkkpmba.com&r=a&t=1601818742&p=v1");
INSERT INTO tbl_contactus VALUES("185","Jeffry Sparkman","sparkman.jeffry@yahoo.com","O L ztudqt","New Message from %title","Hey, do you need any track for your company music?\nIf so, tell us about it and we might give you or make one for you without payment.\nhttps://www.youtube.com/watch?v=IxZdvejWGJ4\nWe will ask only for credits that we did the track. Thank you!");
INSERT INTO tbl_contactus VALUES("186","Latesha Peterson","latesha.peterson83@googlemail.com","Opa Fqhs q","","Looking for fresh buyers? Receive tons of people who are ready to buy sent directly to your website. Boost revenues quick. Start seeing results in as little as 48 hours. For more info Visit: http://bit.ly/buy-website-visitors");
INSERT INTO tbl_contactus VALUES("187","Dena Bromham","dena.bromham@gmail.com","Iwtzye Tpy","","Completely Free advertising, submit your site now and start getting new visitors. Visit: http://www.completely-free-ad-posting.xyz");
INSERT INTO tbl_contactus VALUES("188","xgVEXOuvnPz","obelreakg@gmail.com","XGhTSJPu","UbKJkDnXZSxy","crQARTeksLBPES");
INSERT INTO tbl_contactus VALUES("189","bRDEdfMiyW","obelreakg@gmail.com","vEurqBHeIb","jXimnzNAR","NTcXVqAjn");
INSERT INTO tbl_contactus VALUES("190","","noreply@garden31.ru","","Dating for everyone. Just do it! Follow this link: http://bit.do/fKfvU?h=a8fa4e99b66f295420c227cf3e1f7cc0&","Dating for everyone. Just do it! Follow this link: http://bit.do/fKfvU?h=a8fa4e99b66f295420c227cf3e1f7cc0&");
INSERT INTO tbl_contactus VALUES("191","XhMFSxCDz","polerstskykg@gmail.com","jEHpbNKOdq","yxGVzgEkaI","pMFLYljdDtfwJQT");
INSERT INTO tbl_contactus VALUES("192","dgSljhesYoq","polerstskykg@gmail.com","LedlcfSxJW","hnvOjkKZyqNVwEPp","OFaZGhskeJrEmg");
INSERT INTO tbl_contactus VALUES("193","Wilburn De Gillern","degillern.wilburn@gmail.com","Sh v ev","","Would you be interested in an advertising service that charges less than $50 every month and delivers tons of people who are ready to buy directly to your website? Check out: http://www.buy-website-traffic.xyz ");
INSERT INTO tbl_contactus VALUES("194","Santiago Salter","santiago.salter@gmail.com","Gkbgtefvgo","I found it.","Good evening people at %domain,\nThis is the email lists I was looking for, they have millions of emails you can contact to get new clients https://b2bworld.store/email-lists\nGood luck!");



DROP TABLE tbl_documents;

CREATE TABLE `tbl_documents` (
  `docid` int(10) NOT NULL AUTO_INCREMENT,
  `category` text NOT NULL,
  `description` text NOT NULL,
  `filename` text NOT NULL,
  PRIMARY KEY (`docid`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=latin1;

INSERT INTO tbl_documents VALUES("13","General","Mandatory Disclosure","MD.pdf");
INSERT INTO tbl_documents VALUES("19","Previous Question Papers","April 2018","M.B.A. ( 2016 PATTERN ) (2).pdf");
INSERT INTO tbl_documents VALUES("20","Previous Question Papers","April 2018 2013 Pattern","M.B.A. ( 2013 PATTERN ).pdf");
INSERT INTO tbl_documents VALUES("21","Previous Question Papers","October 2017 2016 Pattern","M.B.A. ( 2016 PATTERN ) (3).pdf");
INSERT INTO tbl_documents VALUES("22","Previous Question Papers","October 2017 2013 Pattern","M.B.A. ( 2013 PATTERN ) (1).pdf");
INSERT INTO tbl_documents VALUES("25","General","MBASyllabus2013CBCGSPattern","MBASyllabus2013CBCGSPattern.pdf");
INSERT INTO tbl_documents VALUES("26","General","Brochure","MIM-Brochure-2016.pdf");
INSERT INTO tbl_documents VALUES("27","General","MBA 2016 Patt sem IV Finance- Indirect Taxation","MBA 2016 Patt sem IV Finance- Indirect Taxation 403 (FIN) with effect from 2017-18_02.012018.pdf");
INSERT INTO tbl_documents VALUES("32","General","Master of Business Administration (MBA) – Revised Syllabus 2019","MBA_Revised Syllabus 2019 23-10-19_24.102019.pdf");



DROP TABLE tbl_enquiry;

CREATE TABLE `tbl_enquiry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  `email` text COLLATE utf8_unicode_ci NOT NULL,
  `contact` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `message` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=122 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;




DROP TABLE tbl_faculty;

CREATE TABLE `tbl_faculty` (
  `id` int(30) NOT NULL AUTO_INCREMENT,
  `type` varchar(15) NOT NULL,
  `name` varchar(100) NOT NULL,
  `designation` varchar(100) NOT NULL,
  `qualification` varchar(100) NOT NULL,
  `experience` int(2) NOT NULL,
  `photo` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=56 DEFAULT CHARSET=latin1;

INSERT INTO tbl_faculty VALUES("1","Teaching","Dr. Dole Bharati Sharad","Director","Mcom,LLB,Phd","36","Dr. Dole Bharati Sharad.jpg");
INSERT INTO tbl_faculty VALUES("54","Teaching","Miss.Chougule Swati Atmaram","Assistant Professor","MBA","1","6d3e8fc436996ba7670a70420aa46671.jpg");
INSERT INTO tbl_faculty VALUES("13","Teaching","Miss.Ranaware Sandhya c","Assistant Professor","MBA","9","Miss.Ranaware Sandhya c.png");
INSERT INTO tbl_faculty VALUES("14","Teaching","Miss.Rasal Pratibha","Assistant Professor","MBA","8","Miss.Rasal Pratibha.png");
INSERT INTO tbl_faculty VALUES("17","Teaching","Dr. Nimbalkar Vipul Virsinh","Assistant Professor","M.com,MBA,SET,NET,Phd ","9","Mr.Nimbalkar Vipul Virsinh.png");
INSERT INTO tbl_faculty VALUES("19","Teaching","Dr.Phadtare Shailaja Dattatray","Assistant Professor","MBA, Ph.D","6","Miss.Phadtare Shailaja Dattatray.png");
INSERT INTO tbl_faculty VALUES("21","Teaching","Mr.Sorate Siddhart Prabhakar ","Assistant Professor","MBA,Phd (Pursuing)","7","Mr.Sorate Siddhart Prabhakar .png");
INSERT INTO tbl_faculty VALUES("29","Non-Teaching","Mr.Pawar Sunil Janardhan","System Admin","B.C.S,MBA (Pursuing)","4","Mr.Pawar Sunil Janardhan.jpg");
INSERT INTO tbl_faculty VALUES("55","Teaching","Miss.Gaikwad Harshada Kishor","Assistant Professor","MBA","1","f4f3506b477f18c3c14d9ba772050d82.jpg");
INSERT INTO tbl_faculty VALUES("53","Non-Teaching","Mr.Kedar Dhananjay Sanjiv","Clerk","B.com","1","90a6ef0efce1062c134082bebfaa234a.jpg");
INSERT INTO tbl_faculty VALUES("32","Non-Teaching","Mr.Jadhav Vaibhav Shivaji","Clerk","B.A","10","Mr.Jadhav Vaibhav Shivaji.png");
INSERT INTO tbl_faculty VALUES("37","Supporting","Mr.Danane Pandurang","Peon","S.S.C","10","Mr.Danane Pandurang.png");
INSERT INTO tbl_faculty VALUES("38","Supporting","Miss.Veer Suvarna S.","Peon","S.S.C","8","Miss.Veer Suvarna S..png");
INSERT INTO tbl_faculty VALUES("43","Supporting","Mr.Waghela Premchand","CLening-T","S.S.C","10","Mr.Waghela Premchand.png");
INSERT INTO tbl_faculty VALUES("45","Supporting","Mr.Kengar Uttam Bapu","Watchman","S.S.C","7","Mr.Kengar Uttam Bapu.png");



DROP TABLE tbl_gallery;

CREATE TABLE `tbl_gallery` (
  `photoid` int(10) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `title` text NOT NULL,
  PRIMARY KEY (`photoid`)
) ENGINE=InnoDB AUTO_INCREMENT=86 DEFAULT CHARSET=latin1;

INSERT INTO tbl_gallery VALUES("70","industrial visit goa.png","Industrial Visit");
INSERT INTO tbl_gallery VALUES("71","01 students at carrer conference.png","Student Carrer Conference");
INSERT INTO tbl_gallery VALUES("72","Career guidence to students by Ashwath Ram- GM cummins.png","Student Carrer Gaidance");
INSERT INTO tbl_gallery VALUES("73","student development.png","Student Devlopment");
INSERT INTO tbl_gallery VALUES("76","Kabbadi 3 Sports.png","Sports");
INSERT INTO tbl_gallery VALUES("79","IMG-20180428-WA0004.jpg","Dr.Phadtare Shailaja Dattatray");
INSERT INTO tbl_gallery VALUES("82","IMG-20190829-WA0047.jpg","Yoga Day");
INSERT INTO tbl_gallery VALUES("83","20190923_152448.jpg","Tree Plantation");
INSERT INTO tbl_gallery VALUES("84","20190923_152649.jpg","Tree Plantation2");
INSERT INTO tbl_gallery VALUES("85","20190923_165038.jpg","Tree Plantation3");



DROP TABLE tbl_login;

CREATE TABLE `tbl_login` (
  `member_id` int(11) NOT NULL AUTO_INCREMENT,
  `UserName` varchar(200) NOT NULL,
  `Password` varchar(200) NOT NULL,
  `FirstName` varchar(200) NOT NULL,
  `LastName` varchar(200) NOT NULL,
  `flag` varchar(1) NOT NULL,
  PRIMARY KEY (`member_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

INSERT INTO tbl_login VALUES("1","mimadmin","Phadtare12#$","Monika","Akhade","Y");
INSERT INTO tbl_login VALUES("2","student","Student@123","Student","Student","N");



DROP TABLE tbl_news;

CREATE TABLE `tbl_news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `newsdate` date NOT NULL,
  `subject` text NOT NULL,
  `description` text NOT NULL,
  `image` varchar(50) NOT NULL,
  `attachment` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=53 DEFAULT CHARSET=latin1;

INSERT INTO tbl_news VALUES("34","2018-06-07","Academic Calender","Academic Calender 2018-19","","Academic Calender-converted.pdf");
INSERT INTO tbl_news VALUES("36","2018-07-05","Remedial Class Timetable ","Remedial Class Timetable 2018-19","","Remedial Class Timetable 2 001-converted.pdf");
INSERT INTO tbl_news VALUES("42","2019-09-20","Against Cap Vacancies Advertisement-2019/2020","Against Cap Vacancies Advertisement-2019/2020","ADD1.jpg","Doc1.pdf");
INSERT INTO tbl_news VALUES("43","2019-09-21","Provisional Merit List Against Cancellation Vacant Seats  ","Provisional Merit List Against Cancellation / Vacant Seats - 2019-20","","PROVISIONAL MERIT LIST 2019-20.pdf");
INSERT INTO tbl_news VALUES("44","2019-09-24","Tree Plantation","As per the norms of Govt.of Maharashtra (33 Crore Plantation) initative.","20190923_152448.jpg","");



